name: Share data between jobs

on: [push]

jobs:
  run-script:
    name: Run script
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v1
      - name: Display the path
        run: echo ${env:PATH}
        shell: pwsh
